import { supabase } from '../supabase';
import { searchTeacherChunks } from './teacher-kb-api';
import { hasActiveSubscription, getTeacherLimits } from './teacher-api';

export interface CAPSLessonPlanParams {
  classId: string;
  subject: string;
  topic: string;
  grade: string;
  term: string;
  date: string;
  duration: string;
  className: string;
  focusAreas: string[];
  includeAssessment: boolean;
  includeDifferentiation: boolean;
  includeResources: boolean;
}

const CAPS_LESSON_PLAN_STRUCTURE = `
You are generating a lesson plan for a South African primary school teacher following the CAPS (Curriculum and Assessment Policy Statement) format required by the Department of Basic Education.

Generate the lesson plan in the EXACT structure below using markdown. Fill in all sections with detailed, practical, grade-appropriate content based on the subject, topic, and any syllabus context provided.

Required CAPS Lesson Plan Structure:

# CAPS Lesson Plan: [Subject] - [Topic]

## School and Teacher Information
- **School:** [School name if available]
- **Teacher:** [Teacher name if available]
- **Grade:** [Grade]
- **Subject:** [Subject]
- **Term:** [Term]
- **Date:** [Date]
- **Duration:** [Duration] minutes
- **Class:** [Class name]

## CAPS Content Area and Topic
- **Content Area:** [Main CAPS content area]
- **Topic:** [Specific topic]
- **CAPS Page Reference:** [Estimated page reference]

## Specific Aims
List 2-3 specific aims from the CAPS document for this subject area.

## Learning Objectives (Content and Concepts)
List 4-5 measurable learning objectives using Bloom's taxonomy verbs. These must align with CAPS requirements for this grade and subject.

## Skills to be Developed
List the specific skills learners will develop, aligned with CAPS skills requirements.

## Prior Knowledge
What learners should already know before this lesson.

## Resources / LTSM (Learner Teacher Support Materials)
- List all materials needed including textbooks, worksheets, manipulatives, technology, etc.

## Lesson Phases

### Phase 1: Introduction / Mental Maths / Warm-up ([time] minutes)
- Detailed warm-up activity to activate prior knowledge
- Engagement hook connecting to learners' real-world experience
- Clear statement of learning objectives to learners

### Phase 2: Direct Instruction / Presentation ([time] minutes)
- Step-by-step explanation of new content
- Use of visual aids and concrete examples
- Key vocabulary and terminology
- Questioning techniques to check understanding
- Worked examples where applicable

### Phase 3: Guided Practice / Classwork ([time] minutes)
- Structured activities with teacher support
- Practice exercises aligned with learning objectives
- Group work or pair work activities where appropriate

### Phase 4: Independent Practice ([time] minutes)
- Individual classwork activities
- Application of learned concepts
- Problem-solving or creative tasks

### Phase 5: Consolidation and Conclusion ([time] minutes)
- Summary of key concepts learned
- Review of learning objectives
- Link to next lesson

## Assessment
### Informal Assessment
- Observation checklist points
- Oral questioning strategies
- Classwork review criteria

### Formal Assessment (if applicable)
- Assessment task description
- Rubric or marking criteria

## Differentiation and Accommodation
### Support for Struggling Learners
- Simplified tasks and scaffolding strategies
- Peer support arrangements
- Additional resources

### Extension for Advanced Learners
- Enrichment activities
- Higher-order thinking challenges
- Independent investigation tasks

### Accommodation for Learners with Barriers
- Visual, auditory, and kinesthetic adaptations
- Language support strategies

## Homework
- Specific homework task linked to lesson objectives
- Expected completion time

## Teacher Reflection (to be completed after the lesson)
- Were the learning objectives achieved?
- What worked well?
- What needs improvement?
- Which learners need additional support?
- How will this inform the next lesson?

---
Generated by GreyEd Teachers | Uhuru AI | CAPS Aligned
`;

export async function generateCAPSLessonPlan(params: CAPSLessonPlanParams) {
  const { data: classData, error: classError } = await supabase
    .from('classes')
    .select('*')
    .eq('id', params.classId)
    .single();

  if (classError) throw classError;

  const isSubscribed = await hasActiveSubscription();

  if (!isSubscribed) {
    const teacherLimits = await getTeacherLimits(classData.teacher_id);
    if (teacherLimits.usedLessonPlans >= teacherLimits.lessonPlans) {
      throw new Error(
        `You've reached your limit of ${teacherLimits.lessonPlans} free lesson plans. Please upgrade for unlimited plans.`
      );
    }
  }

  let syllabusContext = '';
  try {
    const chunks = await searchTeacherChunks(params.subject, params.topic, params.grade);
    if (chunks.length > 0) {
      syllabusContext = chunks
        .map((c) => c.content)
        .join('\n\n')
        .slice(0, 4000);
    }
  } catch {
    // KB chunks not available, proceed without
  }

  const systemPrompt = `${CAPS_LESSON_PLAN_STRUCTURE}

${syllabusContext ? `\n\nCAPS SYLLABUS CONTEXT FOR THIS TOPIC:\n${syllabusContext}\n\nUse the above syllabus context to make the lesson plan accurate and specific to the CAPS requirements. Reference specific content, skills, and assessment standards from the context.` : ''}

IMPORTANT RULES:
- Generate ONLY the lesson plan content, no preamble or explanation.
- All content must be appropriate for ${params.grade} level in South Africa.
- Time allocations for each phase must add up to ${params.duration} minutes total.
- Use South African English spelling conventions.
- Include culturally relevant examples for South African learners.
- Reference CAPS-specific terminology and frameworks.`;

  const userMessage = `Generate a complete CAPS-aligned lesson plan with:
- Subject: ${params.subject}
- Topic: ${params.topic}
- Grade: ${params.grade}
- Term: ${params.term}
- Date: ${params.date}
- Duration: ${params.duration} minutes
- Class: ${params.className}
${params.focusAreas.length > 0 ? `- Focus Areas: ${params.focusAreas.join(', ')}` : ''}
${params.includeAssessment ? '- Include detailed assessment section' : '- Minimal assessment'}
${params.includeDifferentiation ? '- Include full differentiation strategies' : '- Basic differentiation only'}
${params.includeResources ? '- Include comprehensive resources list' : '- Basic resources only'}`;

  const { data: { session } } = await supabase.auth.getSession();
  if (!session?.access_token) throw new Error('Not authenticated');

  const response = await fetch(
    `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/el-ai-teacher`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${session.access_token}`,
        'Content-Type': 'application/json',
        'apikey': import.meta.env.VITE_SUPABASE_ANON_KEY,
      },
      body: JSON.stringify({
        message: userMessage,
        conversationHistory: [],
        teacherContext: {
          subjectArea: params.subject,
          gradeLevel: params.grade,
          examBoard: 'CAPS',
          className: params.className,
          specialConsiderations: params.focusAreas,
        },
        systemPromptOverride: systemPrompt,
      }),
    }
  );

  if (!response.ok) {
    throw new Error('Failed to generate lesson plan');
  }

  const result = await response.json();
  const lessonPlanMarkdown = result.response || result.message || '';

  const meta = {
    subject: params.subject,
    topic: params.topic,
    grade: params.grade,
    term: params.term,
    duration: parseInt(params.duration),
    syllabus: 'CAPS',
    focusAreas: params.focusAreas,
    hasKbContext: syllabusContext.length > 0,
  };

  const { data, error } = await supabase
    .from('lesson_plans')
    .insert([
      {
        class_id: params.classId,
        date: params.date,
        topic: `${params.subject} - ${params.topic}`,
        md_path: lessonPlanMarkdown,
        meta,
        status: 'draft',
      },
    ])
    .select();

  if (error) throw error;

  return {
    markdown: lessonPlanMarkdown,
    meta,
    savedPlan: data && data.length > 0 ? data[0] : null,
  };
}
