/*
  # Neurodiversity Courses System

  1. New Tables
    - `courses`
      - `id` (bigint, primary key)
      - `title` (text)
      - `description` (text)
      - `duration_minutes` (integer)
      - `module_count` (integer)
      - `content` (jsonb) - stores module content
      - `created_at` (timestamptz)

    - `teacher_course_progress`
      - `id` (bigint, primary key)
      - `teacher_id` (uuid, references auth.users)
      - `course_id` (bigint, references courses)
      - `completed_modules` (integer array)
      - `quiz_score` (integer)
      - `quiz_passed` (boolean)
      - `completed_at` (timestamptz)
      - `created_at` (timestamptz)

    - `teacher_certificates`
      - `id` (bigint, primary key)
      - `teacher_id` (uuid, references auth.users)
      - `course_id` (bigint, references courses)
      - `certificate_url` (text)
      - `issued_at` (timestamptz)

  2. Security
    - Enable RLS on all tables
    - Teachers can only view and update their own progress
    - Courses table is readable by all authenticated teachers

  3. Initial Data
    - Insert "Understanding Neurodivergence" course with 4 modules
*/

CREATE TABLE IF NOT EXISTS courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  duration_minutes INTEGER DEFAULT 10,
  module_count INTEGER DEFAULT 4,
  content JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE courses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated teachers can view courses"
  ON courses
  FOR SELECT
  TO authenticated
  USING (true);

CREATE TABLE IF NOT EXISTS teacher_course_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES auth.users ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  completed_modules INTEGER[] DEFAULT ARRAY[]::INTEGER[],
  quiz_score INTEGER DEFAULT 0,
  quiz_passed BOOLEAN DEFAULT false,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(teacher_id, course_id)
);

ALTER TABLE teacher_course_progress ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Teachers can view own course progress"
  ON teacher_course_progress
  FOR SELECT
  TO authenticated
  USING (teacher_id = auth.uid());

CREATE POLICY "Teachers can insert own course progress"
  ON teacher_course_progress
  FOR INSERT
  TO authenticated
  WITH CHECK (teacher_id = auth.uid());

CREATE POLICY "Teachers can update own course progress"
  ON teacher_course_progress
  FOR UPDATE
  TO authenticated
  USING (teacher_id = auth.uid())
  WITH CHECK (teacher_id = auth.uid());

CREATE TABLE IF NOT EXISTS teacher_certificates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  teacher_id UUID REFERENCES auth.users ON DELETE CASCADE,
  course_id BIGINT REFERENCES courses(id) ON DELETE CASCADE,
  certificate_data JSONB NOT NULL,
  issued_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(teacher_id, course_id)
);

ALTER TABLE teacher_certificates ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Teachers can view own certificates"
  ON teacher_certificates
  FOR SELECT
  TO authenticated
  USING (teacher_id = auth.uid());

CREATE POLICY "Teachers can insert own certificates"
  ON teacher_certificates
  FOR INSERT
  TO authenticated
  WITH CHECK (teacher_id = auth.uid());

INSERT INTO courses (title, description, duration_minutes, module_count, content)
VALUES (
  'Understanding Neurodivergence',
  'Teacher-facing micro-course covering neurodiversity basics, classroom signals, accommodations, and GreyEd tools.',
  10,
  4,
  '{
    "modules": [
      {
        "id": 1,
        "title": "What Neurodiversity Is and Isn''t",
        "duration": 2.5,
        "objectives": [
          "Define neurodiversity and name common profiles (dyslexia, ADHD)",
          "Shift to a strengths-based lens"
        ],
        "keyIdeas": [
          "Natural brain variation; supports remove barriers",
          "Design the classroom, not the learner"
        ],
        "quickAction": "Identify one instruction you can simplify (shorter sentence, fewer steps)",
        "content": "Neurodiversity describes natural variation in how brains work. Common profiles include dyslexia, ADHD, autism, and others. Rather than deficits to fix, these are differences requiring supportive environments. Accommodations level the playing field by removing barriers—not lowering standards. When we design accessible classrooms, we serve all learners better."
      },
      {
        "id": 2,
        "title": "Spotting Classroom Signals",
        "duration": 2.5,
        "objectives": [
          "Recognize signals for dyslexia and ADHD",
          "Separate access barrier from skill gap"
        ],
        "signals": {
          "dyslexia": [
            "Slow/effortful decoding",
            "Spelling inconsistency",
            "Avoids reading aloud"
          ],
          "adhd": [
            "Initiation difficulty",
            "Sustained attention dips",
            "Working-memory slips"
          ]
        },
        "barrierScan": "Is it the text format? pacing? task complexity?",
        "quickAction": "Run a barrier scan before your next activity",
        "content": "Learning to spot neurodivergent signals helps you provide timely support. For dyslexia, watch for slow decoding, inconsistent spelling, and reading avoidance. For ADHD, notice difficulty starting tasks, attention fluctuations, and working memory challenges. Before assuming a skill gap, run a 60-second barrier scan: Could this be the text format, pacing, or task complexity creating the difficulty?"
      },
      {
        "id": 3,
        "title": "Low-Effort Accommodations That Work",
        "duration": 2.5,
        "objectives": [
          "Apply 3 practical supports without rewriting a lesson"
        ],
        "accommodations": {
          "textTweaks": [
            "Larger line-spacing (1.5–2.0)",
            "Shorter lines",
            "Clear headings",
            "Left-aligned text"
          ],
          "taskTweaks": [
            "Chunk steps",
            "I do → We do → You do",
            "Time-boxed focus + micro-breaks"
          ],
          "responseChoice": [
            "Oral responses",
            "Multiple choice",
            "Word banks"
          ]
        },
        "quickAction": "Turn on Dyslexia Mode for one handout and add numbered steps",
        "content": "Effective accommodations don''t require lesson rewrites. Text tweaks: increase line spacing to 1.5-2.0, keep lines short, use clear headings, and left-align text. Task tweaks: chunk instructions, use gradual release (I do, We do, You do), and build in timed focus periods with micro-breaks. Response options: offer oral responses, multiple choice, or word banks. These small changes dramatically improve access."
      },
      {
        "id": 4,
        "title": "Using GreyEd to Support Learners",
        "duration": 2.5,
        "objectives": [
          "Generate dyslexia-ready artifacts and scaffolds with Neuro-Assist",
          "Use Student Mode for drills; read weekly signals"
        ],
        "greyedFeatures": {
          "generate": "Lesson plans + handouts with toggles for spacing, simplification, word banks",
          "studentMode": "Speed reading, working-memory, writing frames",
          "review": "Weekly Outcomes Card with common errors and suggested supports"
        },
        "quickAction": "Create one scaffolded activity for tomorrow''s class",
        "content": "GreyEd''s Neuro-Assist streamlines neurodiversity support. When generating lesson plans and handouts, toggle options for dyslexia-friendly spacing, language simplification, and word banks. Student Mode offers speed reading drills, working memory exercises, and writing frames. The Weekly Outcomes Card highlights common student errors with targeted support suggestions. Start today by creating one scaffolded activity for your next class."
      }
    ],
    "cheatSheet": {
      "signals": {
        "dyslexia": ["Decoding effort", "Inconsistent spelling", "Reading avoidance"],
        "adhd": ["Initiation", "Attention", "Working-memory hurdles"]
      },
      "quickSupports": [
        "Increase spacing",
        "Shorter lines",
        "Number steps",
        "Provide exemplar",
        "Offer response choice",
        "Add micro-breaks"
      ],
      "greyedClicks": "Generate → Toggle Dyslexia Mode → Add Word Bank → Export PDF",
      "parentTalkTrack": "We''re adjusting how materials look and how tasks are broken into steps to make learning easier at home and school."
    },
    "quiz": [
      {
        "id": 1,
        "question": "Neurodiversity refers to natural variation in how brains work, requiring supportive environments rather than fixes.",
        "type": "true-false",
        "correctAnswer": "true",
        "explanation": "Neurodiversity recognizes brain differences as natural variation, not deficits."
      },
      {
        "id": 2,
        "question": "Which is NOT a dyslexia classroom signal?",
        "type": "multiple-choice",
        "options": [
          "Slow decoding",
          "Inconsistent spelling",
          "Hyperactive behavior",
          "Reading avoidance"
        ],
        "correctAnswer": "Hyperactive behavior",
        "explanation": "Hyperactive behavior is typically associated with ADHD, not dyslexia."
      },
      {
        "id": 3,
        "question": "What is the recommended line spacing for dyslexia-friendly text?",
        "type": "multiple-choice",
        "options": [
          "1.0",
          "1.5–2.0",
          "2.5–3.0",
          "Single spacing"
        ],
        "correctAnswer": "1.5–2.0",
        "explanation": "Line spacing of 1.5 to 2.0 significantly improves readability for dyslexic readers."
      },
      {
        "id": 4,
        "question": "The ''I do, We do, You do'' approach is an example of:",
        "type": "multiple-choice",
        "options": [
          "Punishment strategy",
          "Gradual release of responsibility",
          "Assessment method",
          "Classroom management"
        ],
        "correctAnswer": "Gradual release of responsibility",
        "explanation": "This scaffolding technique gradually transfers responsibility from teacher to student."
      },
      {
        "id": 5,
        "question": "GreyEd''s Student Mode includes which support tools?",
        "type": "multiple-choice",
        "options": [
          "Only reading drills",
          "Only writing frames",
          "Speed reading, working memory, and writing frames",
          "Grade calculation only"
        ],
        "correctAnswer": "Speed reading, working memory, and writing frames",
        "explanation": "Student Mode provides comprehensive support including reading, memory, and writing tools."
      }
    ]
  }'
) ON CONFLICT DO NOTHING;