/*
  # Create tables for GreyEd Teachers platform

  1. New Tables
    - `classes`: For teacher class management
    - `lesson_plans`: Stores AI-generated lesson plans
    - `resources`: Teaching materials uploaded by teachers
    - `assessments`: Quiz/test configurations
    - `assessment_items`: Individual questions in assessments
    - `grades`: Student assessment results
    - `family_updates`: Weekly parent/guardian communication

  2. Security
    - Enable RLS on all tables
    - Add policies to ensure teachers can only access their own data

  3. Schema Details
    - All tables reference the teacher's user ID
    - Proper relationships established between tables
    - Support for AI-generated content
*/

-- Create classes table (core table for teacher functionality)
CREATE TABLE IF NOT EXISTS classes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  teacher_id UUID REFERENCES auth.users ON DELETE CASCADE,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  grade TEXT NOT NULL,
  student_count INTEGER DEFAULT 0,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on classes
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;

-- Create policy for teachers to manage their own classes
CREATE POLICY "Teachers can manage their own classes"
  ON classes
  FOR ALL
  USING (teacher_id = auth.uid())
  WITH CHECK (teacher_id = auth.uid());

-- Create lesson_plans table
CREATE TABLE IF NOT EXISTS lesson_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id UUID REFERENCES classes(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  topic TEXT NOT NULL,
  md_path TEXT,
  meta JSONB,
  status TEXT CHECK (status IN ('draft', 'ready', 'taught')),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on lesson_plans
ALTER TABLE lesson_plans ENABLE ROW LEVEL SECURITY;

-- Create policy for lesson plans
CREATE POLICY "Teachers can manage lesson plans for their classes"
  ON lesson_plans
  FOR ALL
  USING (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  )
  WITH CHECK (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  );

-- Create resources table
CREATE TABLE IF NOT EXISTS resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id UUID REFERENCES classes(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  file_name TEXT,
  file_type TEXT,
  file_size INTEGER,
  tags TEXT[],
  uploaded_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on resources
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;

-- Create policy for resources
CREATE POLICY "Teachers can manage resources for their classes"
  ON resources
  FOR ALL
  USING (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  )
  WITH CHECK (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  );

-- Create assessments table
CREATE TABLE IF NOT EXISTS assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id UUID REFERENCES classes(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'completed')),
  generated BOOLEAN DEFAULT TRUE,
  assessment_type TEXT,
  difficulty TEXT,
  topic TEXT,
  question_count INTEGER,
  average_score NUMERIC,
  submission_rate TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on assessments
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;

-- Create policy for assessments
CREATE POLICY "Teachers can manage assessments for their classes"
  ON assessments
  FOR ALL
  USING (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  )
  WITH CHECK (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  );

-- Create assessment_items table
CREATE TABLE IF NOT EXISTS assessment_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id BIGINT REFERENCES assessments(id) ON DELETE CASCADE,
  question TEXT NOT NULL,
  correct_answer TEXT NOT NULL,
  metadata JSONB
);

-- Enable RLS on assessment_items
ALTER TABLE assessment_items ENABLE ROW LEVEL SECURITY;

-- Create policy for assessment items
CREATE POLICY "Teachers can manage assessment items for their assessments"
  ON assessment_items
  FOR ALL
  USING (
    assessment_id IN (
      SELECT a.id FROM assessments a
      JOIN classes c ON a.class_id = c.id
      WHERE c.teacher_id = auth.uid()
    )
  )
  WITH CHECK (
    assessment_id IN (
      SELECT a.id FROM assessments a
      JOIN classes c ON a.class_id = c.id
      WHERE c.teacher_id = auth.uid()
    )
  );

-- Create grades table
CREATE TABLE IF NOT EXISTS grades (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_item_id BIGINT REFERENCES assessment_items(id) ON DELETE CASCADE,
  student_id TEXT NOT NULL,
  student_name TEXT,
  score NUMERIC,
  response TEXT,
  graded_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on grades
ALTER TABLE grades ENABLE ROW LEVEL SECURITY;

-- Create policy for grades
CREATE POLICY "Teachers can manage grades for their assessments"
  ON grades
  FOR ALL
  USING (
    assessment_item_id IN (
      SELECT ai.id FROM assessment_items ai
      JOIN assessments a ON ai.assessment_id = a.id
      JOIN classes c ON a.class_id = c.id
      WHERE c.teacher_id = auth.uid()
    )
  )
  WITH CHECK (
    assessment_item_id IN (
      SELECT ai.id FROM assessment_items ai
      JOIN assessments a ON ai.assessment_id = a.id
      JOIN classes c ON a.class_id = c.id
      WHERE c.teacher_id = auth.uid()
    )
  );

-- Create family_updates table
CREATE TABLE IF NOT EXISTS family_updates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id UUID REFERENCES classes(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  html_path TEXT NOT NULL,
  sent BOOLEAN DEFAULT FALSE,
  sent_date TIMESTAMPTZ,
  open_count INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS on family_updates
ALTER TABLE family_updates ENABLE ROW LEVEL SECURITY;

-- Create policy for family updates
CREATE POLICY "Teachers can manage family updates for their classes"
  ON family_updates
  FOR ALL
  USING (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  )
  WITH CHECK (
    class_id IN (
      SELECT id FROM classes WHERE teacher_id = auth.uid()
    )
  );

-- Create teacher_preferences table
CREATE TABLE IF NOT EXISTS teacher_preferences (
  teacher_id UUID REFERENCES auth.users ON DELETE CASCADE,
  notification_settings JSONB,
  other_settings JSONB,
  updated_at TIMESTAMPTZ DEFAULT now(),
  PRIMARY KEY (teacher_id)
);

-- Enable RLS on teacher_preferences
ALTER TABLE teacher_preferences ENABLE ROW LEVEL SECURITY;

-- Create policy for teacher preferences
CREATE POLICY "Teachers can manage their own preferences"
  ON teacher_preferences
  FOR ALL
  USING (teacher_id = auth.uid())
  WITH CHECK (teacher_id = auth.uid());

-- Add additional profile fields for teachers
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS school TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS title TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS subjects TEXT[];
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bio TEXT;