/*
  # Create Schema for Student Side Application

  1. New Tables
    - Ensures proper RLS for student-specific data
    - Updates profile table to track plan type
    - Adds relationship between user_id and student role

  2. Security
    - All tables have RLS enabled
    - Policies ensure students can only access their own data
*/

-- Add plan column to profiles if it doesn't exist
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS plan text DEFAULT 'free' CHECK (plan IN ('free', 'premium'));

-- Add avatar_config column to profiles for personalized avatar settings
ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS avatar_config jsonb;

-- Create chat_messages table if it doesn't exist
CREATE TABLE IF NOT EXISTS chat_messages (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  role text CHECK (role IN ('user', 'assistant')),
  content text,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS on chat_messages
ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

-- Create policies for chat_messages
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'chat_messages' AND policyname = 'Users can insert own chat messages'
  ) THEN
    CREATE POLICY "Users can insert own chat messages"
      ON chat_messages
      FOR INSERT
      TO public
      WITH CHECK (auth.uid() = user_id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'chat_messages' AND policyname = 'Users can read own chat messages'
  ) THEN
    CREATE POLICY "Users can read own chat messages"
      ON chat_messages
      FOR SELECT
      TO public
      USING (auth.uid() = user_id);
  END IF;
END
$$;

-- Ensure timetable_entries table has all necessary fields
ALTER TABLE timetable_entries 
ADD COLUMN IF NOT EXISTS type text DEFAULT 'study' 
CHECK (type IN ('study', 'assignment', 'exam', 'break'));